from __future__ import annotations

import pytest

from coreflow.pulse_counter import (
    PulseAnalysisConfig,
    analyze_dsview_csv,
    calculate_measured_pulse_error,
    calculate_measured_pulse_k_factor,
    read_dsview_csv,
)


def test_dsview_csv_analysis_counts_configured_edges_and_quantity(tmp_path) -> None:
    csv_path = tmp_path / "dsview.csv"
    csv_path.write_text(
        "\n".join(
            [
                "; CSV, generated by libsigrok4DSL 0.2.0 on Wed Mar 18 15:49:14 2026",
                "; Channels (3/16)",
                "; Sample rate: 25 MHz",
                "; Sample count: 1 M Samples",
                "Time(s), 0, 1, 2",
                "0,0,0,0",
                "0.001,1,0,0",
                "0.0015,0,0,0",
                "0.011,1,0,0",
                "0.0115,0,0,0",
                "0.021,1,0,0",
                "0.0215,0,0,0",
            ]
        ),
        encoding="utf-8",
    )

    capture = read_dsview_csv(csv_path)
    result = analyze_dsview_csv(
        csv_path,
        PulseAnalysisConfig(
            channel="0",
            edge="rising",
            pulse_value=0.05,
            unit="g",
            switch_frequency_hz=100.0,
        ),
    )

    assert capture.metadata.sample_rate_hz == pytest.approx(25_000_000.0)
    assert capture.channels == ("0", "1", "2")
    assert result.pulse_count == 3
    assert result.total_quantity == pytest.approx(0.15)
    assert result.mean_rate == pytest.approx(7.5)
    assert [edge.time_s for edge in result.edges] == pytest.approx(
        [0.001, 0.011, 0.021]
    )


def test_dsview_csv_analysis_uses_switch_period_windows_and_flags_boundary_pulses(
    tmp_path,
) -> None:
    csv_path = tmp_path / "switching.csv"
    csv_path.write_text(
        "\n".join(
            [
                "; CSV, generated by libsigrok4DSL 0.2.0",
                "; Channels (1/16)",
                "; Sample rate: 25 MHz",
                "; Sample count: 1 M Samples",
                "Time(s), 0",
                "0,0",
                "0.001,1",
                "0.0015,0",
                "0.00999,1",
                "0.009995,0",
                "0.01001,1",
                "0.01051,0",
                "0.019,1",
                "0.0195,0",
            ]
        ),
        encoding="utf-8",
    )

    result = analyze_dsview_csv(
        csv_path,
        PulseAnalysisConfig(
            channel="0",
            pulse_value=0.05,
            switch_frequency_hz=100.0,
            boundary_tolerance_s=0.00005,
        ),
    )

    assert [window.pulse_count for window in result.windows] == [2, 2]
    assert [window.rate for window in result.windows] == pytest.approx([10.0, 10.0])
    assert result.windows[0].boundary_pulse_count == 1
    assert result.windows[1].boundary_pulse_count == 1
    assert result.boundary_pulse_count == 2


def test_dsview_csv_analysis_detects_frequency_segments_from_switch_windows(
    tmp_path,
) -> None:
    csv_path = tmp_path / "segments.csv"
    csv_path.write_text(
        "\n".join(
            [
                "; CSV, generated by libsigrok4DSL 0.2.0",
                "; Channels (1/16)",
                "; Sample rate: 25 MHz",
                "; Sample count: 1 M Samples",
                "Time(s), 0",
                "0,0",
                "0.001,1",
                "0.0012,0",
                "0.006,1",
                "0.0062,0",
                "0.011,1",
                "0.0112,0",
                "0.012,1",
                "0.0122,0",
            ]
        ),
        encoding="utf-8",
    )

    result = analyze_dsview_csv(
        csv_path,
        PulseAnalysisConfig(
            channel="0",
            pulse_value=0.05,
            switch_frequency_hz=100.0,
            min_segment_pulses=1,
        ),
    )

    assert [segment.pulse_count for segment in result.frequency_segments] == [2, 2]
    assert [segment.mean_frequency_hz for segment in result.frequency_segments] == (
        pytest.approx([200.0, 1000.0])
    )
    assert [segment.mean_rate for segment in result.frequency_segments] == pytest.approx(
        [10.0, 50.0]
    )


def test_measured_pulse_calibration_preview_formulas() -> None:
    error = calculate_measured_pulse_error(
        measured_quantity=52.5,
        standard_quantity=50.0,
    )
    k_factor = calculate_measured_pulse_k_factor(
        current_k_factor=1200.0,
        measured_quantity=52.5,
        standard_quantity=50.0,
    )

    assert error.percent_error == pytest.approx(5.0)
    assert k_factor.corrected_k_factor == pytest.approx(1142.857142857)
