"""Parser for DSView/libsigrok4DSL compressed CSV exports."""

from __future__ import annotations

import csv
from pathlib import Path
import re

from coreflow.pulse_counter.models import (
    DsviewCsvCapture,
    DsviewCsvMetadata,
    DsviewCsvSample,
)


def read_dsview_csv(path: str | Path) -> DsviewCsvCapture:
    """Read a DSView CSV export whose rows represent signal state changes."""

    source_path = Path(path)
    comments: list[str] = []
    header: list[str] | None = None
    rows: list[DsviewCsvSample] = []
    with source_path.open(newline="", encoding="utf-8-sig") as stream:
        for raw_line in stream:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith(";"):
                comments.append(line)
                continue
            header = [column.strip() for column in line.split(",")]
            break
        if header is None:
            raise ValueError("DSView CSV has no header row.")
        if not header or header[0] != "Time(s)":
            raise ValueError("DSView CSV must start with a Time(s) column.")
        channels = tuple(header[1:])
        if not channels:
            raise ValueError("DSView CSV must contain at least one channel column.")
        reader = csv.DictReader(stream, fieldnames=header)
        for row in reader:
            if not row or not row.get("Time(s)"):
                continue
            rows.append(
                DsviewCsvSample(
                    time_s=float(str(row["Time(s)"]).strip()),
                    states={
                        channel: _parse_state(row[channel], channel=channel)
                        for channel in channels
                    },
                )
            )
    if not rows:
        raise ValueError("DSView CSV contains no sample rows.")
    return DsviewCsvCapture(
        metadata=_parse_metadata(comments, source_path=source_path),
        channels=channels,
        samples=tuple(rows),
    )


def _parse_state(value: object, *, channel: str) -> int:
    try:
        state = int(str(value).strip())
    except Exception as exc:
        raise ValueError(f"Invalid logic state for channel {channel}: {value}") from exc
    if state not in (0, 1):
        raise ValueError(f"Logic state for channel {channel} must be 0 or 1.")
    return state


def _parse_metadata(
    comments: list[str],
    *,
    source_path: Path,
) -> DsviewCsvMetadata:
    generator: str | None = None
    enabled_channel_count: int | None = None
    channel_count: int | None = None
    sample_rate_hz: float | None = None
    sample_count: str | None = None
    for comment in comments:
        text = comment[1:].strip() if comment.startswith(";") else comment.strip()
        if text.startswith("CSV, generated by "):
            generator = text.removeprefix("CSV, generated by ")
        elif text.startswith("Channels"):
            match = re.search(r"\((\d+)\s*/\s*(\d+)\)", text)
            if match:
                enabled_channel_count = int(match.group(1))
                channel_count = int(match.group(2))
        elif text.startswith("Sample rate:"):
            sample_rate_hz = _parse_rate_hz(text.removeprefix("Sample rate:").strip())
        elif text.startswith("Sample count:"):
            sample_count = text.removeprefix("Sample count:").strip()
    return DsviewCsvMetadata(
        source_path=source_path,
        generator=generator,
        channel_count=channel_count,
        enabled_channel_count=enabled_channel_count,
        sample_rate_hz=sample_rate_hz,
        sample_count=sample_count,
        comments=tuple(comments),
    )


def _parse_rate_hz(text: str) -> float:
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)\s*([kKmMgG]?)Hz", text)
    if not match:
        raise ValueError(f"Unsupported sample-rate format: {text}")
    value = float(match.group(1))
    scale = match.group(2).lower()
    multiplier = {
        "": 1.0,
        "k": 1_000.0,
        "m": 1_000_000.0,
        "g": 1_000_000_000.0,
    }[scale]
    return value * multiplier
